<!DOCTYPE html>
<html>
	<head>
		<title>RMA</title>
		<link rel="stylesheet" type="text/css" href="style.css">
		<meta charset="Utf-8">
		<link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
	</head>
	<body>
		<div class="glxavor">
			<?php  
				include("header.php");
				include("menu.php");
			?>
<!-- ___________________container_____________ -->
			<div class="container6">
				<h1>History</h1>
				<p>
					Real Madrid's origins go back to when football was introduced to Madrid by the academics and students of the Institución Libre de Enseñanza, which included several Cambridge and Oxford University graduates. They founded Football Club Sky in 1897, playing on Sunday mornings at Moncloa. It split into two clubs in 1900: New Foot-Ball de Madrid and Madrid Football Club. On 6 March 1902, after a new Board presided by Juan Padrós had been elected, Madrid Football Club was officially founded. Three years after its foundation, in 1905, Madrid FC won its first title after defeating Athletic Bilbao in the Spanish Cup final. The club became one of the founding sides of the Royal Spanish Football Federation on 4 January 1909, when club president Adolfo Meléndez signed the foundation agreement of the Spanish FA. After moving between grounds the team moved to the Campo de O'Donnell in 1912. In 1920, the club's name was changed to Real Madrid after King Alfonso XIII granted the title of Real (Royal) to the club.
					In 1929, the first Spanish football league was founded. Real Madrid led the first league season until the last match, a loss to Athletic Bilbao, meant they finished runners-up to Barcelona. Real Madrid won its first League title in the 1931–32 season. Real won the League again the following year, becoming the first team to have won the championship twice.
					On 14 April 1931, the arrival of the Second Spanish Republic caused the club to lose the title Real and went back to being named Madrid Football Club. Football continued during the Second World War, and on 13 June 1943 Madrid beat Barcelona 11–1 in the second leg of a semi-final of the Copa del Generalísimo, the Copa del Rey having been renamed in honour of General Franco. It has been suggested that Barcelona players were intimidated by police, including by the director of state security who "allegedly told the team that some of them were only playing because of the regime's generosity in permitting them to remain in the country." The Barcelona chairman, Enric Piñeyro, was assaulted by Madrid fans. However, none of these allegations have been proven and FIFA and UEFA still consider the result as legitimate. According to Spanish journalist and writer, Juan Carlos Pasamontes, Barcelona player Josep Valle denied that the Spanish security forces came before the match. Instead, at the end of the first half, Barcelona coach Juan José Nogués and all of his players were angry with the hard-style of play Real Madrid was using and with the aggressiveness of the home crowd. When they refused to take the field, the Superior Chief of Police of Madrid appeared, identified himself, and ordered the team to take the field.
					Santiago Bernabéu Yeste became president of Real Madrid in 1945. Under his presidency, the club, its stadium Santiago Bernabéu and its training facilities Ciudad Deportiva were rebuilt after the Spanish Civil War damages. Additionally, during the 1950s former Real Madrid Amateurs player Miguel Malbo founded Real Madrid's youth academy, or "cantera," known today as La Fábrica. Beginning in 1953, he embarked upon a strategy of signing world-class players from abroad, the most prominent being Alfredo Di Stéfano.
					Amancio Amaro, captain of the Yé-yé
					In 1955, acting upon the idea proposed by the French sports journalist and editor of L'Équipe Gabriel Hanot, Bernabéu, Bedrignan and Gusztáv Sebes created an exhibition tournament of invited teams from around Europe that would eventually become what today is known as the UEFA Champions League. It was under Bernabéu's guidance that Real Madrid established itself as a major force in both Spanish and European football. The club won the European Cup five times in a row between 1956 and 1960, which included the 7–3 Hampden Park final against Eintracht Frankfurt in 1960. After these five consecutive successes, Real was permanently awarded the original cup and earning the right to wear the UEFA badge of honour.
					The club won the European Cup for a sixth time in 1966 defeating Partizan Belgrade 2–1 in the final with a team composed entirely of same nationality players, a first in the competition. This team became known as the Yé-yé. The name "Ye-yé" came from the "Yeah, yeah, yeah" chorus in The Beatles' song "She Loves You" after four members of the team posed for Marca and impersonated the Beatles. The Ye-yé generation was also European Cup runner-up in 1962 and 1964. In the 1970s, Real Madrid won five league championships and three Spanish Cups. The club played its first UEFA Cup Winners' Cup final in 1971 and lost to English side Chelsea 2–1. On 2 July 1978, club president Santiago Bernabéu died while the World Cup was being played in Argentina. FIFA decreed three days of mourning to honour him during the tournament. The following year, the club organized the first edition of the Trofeo Santiago Bernabéu in the memory of its former president.
					By the early 1980s, Real Madrid had lost its grasp on the Liga title until a new cohort of home-grown stars brought domestic success back to the club. Spanish sport journalist Julio César Iglesias gave to this generation the name La Quinta del Buitre ("Vulture's Cohort"), which was derived from the nickname given to one of its members, Emilio Butragueño. The other four members were Manuel Sanchís, Martín Vázquez, Míchel and Miguel Pardeza; all five footballers were graduates of Real Madrid's youth academy. With La Quinta del Buitre (reduced to four members when Pardeza left for Zaragoza in 1986) and notable players like goalkeeper Francisco Buyo, right-back Miguel Porlán Chendo and Mexican striker Hugo Sánchez, Real Madrid had one of the best teams in Spain and Europe during the second half of the 1980s, winning two UEFA Cups, five Spanish championships in a row, one Spanish cup and three Spanish Super Cups. In the early 1990s, La Quinta del Buitre split up after Martín Vázquez, Emilio Butragueño and Míchel left the club.
					In 1996, President Lorenzo Sanz appointed Fabio Capello as coach. Although his tenure lasted only one season, Real Madrid was proclaimed league champion and players like Roberto Carlos, Predrag Mijatović, Davor Šuker and Clarence Seedorf arrived at the club to strengthen a squad that already boasted the likes of Raúl, Fernando Hierro, Iván Zamorano, and Fernando Redondo. As a result, Real Madrid (with the addition of Fernando Morientes in 1997) finally ended its 32-year wait for its seventh European Cup: in 1998, under manager Jupp Heynckes, they defeated Juventus 1–0 in the final with a goal from Predrag Mijatović.
					In July 2000, Florentino Pérez was elected club president. He vowed in his campaign to erase the club's €270 million debt and modernize the club's facilities. However, the primary electoral promise that propelled Pérez to victory was the signing of Luís Figo from arch-rivals Barcelona. The following year, the club had its training ground rezoned and used the money to begin assembling the Galácticos team by signing a global star every summer, which included Zinedine Zidane, Ronaldo, Luís Figo, Roberto Carlos, Raúl, David Beckham and Fabio Cannavaro. It is debatable whether the gamble paid off, as despite winning the UEFA Champions League and an Intercontinental Cup in 2002, followed by La Liga in 2003, the club failed to win a major trophy for the next three seasons.
					The few days after the capturing of the 2003 Liga title were surrounded with controversy. The first controversial decision came when Pérez sacked winning coach Vicente del Bosque. Over a dozen players left the club, including Madrid captain Fernando Hierro, while defensive midfielder Claude Makélélé refused to take part in training in protest at being one of the lowest-paid players at the club and subsequently moved to Chelsea. "That's a lot [of players leaving] when the normal rule is: never change a winning team," stated Zidane. Real Madrid, with newly appointed coach Carlos Queiroz, started their domestic league slowly after a hard win over Real Betis.</p>
					<div class="nkarzidan">
						<img src="nkarner/nkar7.jpg">
					</div>
					<p>
					The 2005–06 season began with the promise of several new signings: Júlio Baptista (€24 million), Robinho (€30 million) and Sergio Ramos (€27 million). However, Real Madrid suffered from some poor results, including a 0–3 loss at the hands of Barcelona at the Santiago Bernabéu in November 2005. Madrid's coach Wanderley Luxemburgo was sacked the following month and his replacement was Juan Ramón López Caro. A brief return to form came to an abrupt halt after losing the first leg of the Copa del Rey quarterfinal, 6–1 to Real Zaragoza. Shortly after, Real Madrid were eliminated from the Champions League for a fourth successive year, this time at the hands of Arsenal. On 27 February 2006, Florentino Pérez resigned.
					Ramón Calderón was elected as club president on 2 July 2006 and subsequently appointed Fabio Capello as the new coach and Predrag Mijatović as the new sporting director. Real Madrid won the Liga title in 2007 for the first time in four years, but Capello was nonetheless sacked at the end of the campaign. On 9 June 2007, Real played against Zaragoza at La Romareda. Zaragoza led Real 2–1 near the end of the match while Barcelona were also winning against Espanyol 2–1. A late Ruud van Nistelrooy equalizer followed by a last-minute Raúl Tamudo goal sprang Real Madrid's title hopes back into their favour.
					The title was won on 17 June, where Real faced Mallorca at the Bernabéu while Barcelona and Sevilla, the other title challengers, faced Gimnàstic de Tarragona and Villarreal, respectively. At half-time, Real were 0–1 down, while Barcelona had surged ahead into a 0–3 lead in Tarragona; however, three goals in the last half-hour secured Madrid a 3–1 win and their first league title since 2003. The first goal came from José Antonio Reyes, who scored after a good work from Gonzalo Higuaín. An own goal followed by another goal from Reyes allowed Real to begin celebrating the title. Thousands of Real Madrid fans began going to Plaza de Cibeles to celebrate the title.
					On 1 June 2009, Florentino Pérez regained Real Madrid's presidency. Pérez continued with the Galácticos policy pursued in his first term, buying Kaká from Milan for a record-breaking sum of £56 million, and then breaking the record again by purchasing Cristiano Ronaldo from Manchester United for £80 million.
					</p>
					<p class="pp1">
					José Mourinho took over as manager in May 2010. In April 2011, a strange occurrence happened when, for the first time ever, four Clásicos were to be played in a span of just 18 days. The first fixture was for the Liga campaign on 17 April (which ended 1–1 with penalty goals for both sides), the Copa del Rey final (which ended 1–0 to Madrid) and the controversial two-legged Champions League semifinal on 27 April and 2 May (3–1 loss on aggregate) to Barcelona.
					In the 2011–12 La Liga season, Real Madrid won La Liga for a record 32nd time in the league's history, also finishing the season with numerous club-level records set, including 100 points reached in a single season, a total of 121 goals scored, a goal difference of +89 and 16 away wins, with 32 wins overall. In the same season, Cristiano Ronaldo become the fastest player to reach 100 goals scored in Spanish league history. In reaching 101 goals in 92 games, Ronaldo surpassed Real Madrid legend Ferenc Puskás, who scored 100 goals in 105 games. Ronaldo set a new club mark for individual goals scored in one year (60), and became the first player ever to score against all 19 opposition teams in a single season.
					Real Madrid began the 2012–13 season winning the Supercopa de España, defeating Barcelona on away goals, but finished as second in the league competition. A major transfer of the season was signing from Tottenham Hotspur of Luka Modrić for a fee in the region of £33 million. In the Champions League, they were drawn in the "group of death" alongside Borussia Dortmund, Manchester City and Ajax, finishing second with three points behind Dortmund. In the round of 16, they defeated Manchester United, Galatasaray in the quarter-finals, and reached their third-straight semi-final finish in the Champions League, when they were again stopped by Dortmund. After a disappointing extra time loss to Atlético Madrid in the 2013 Copa del Rey Final, Pérez announced the departure of José Mourinho at the end of the season by "mutual agreement."</p>
					<div class="nkarnkar1">
						<img src="nkarner/nkar12.jpg">
					</div>
					<p class="pp2">
					On 25 June 2013, Carlo Ancelotti succeeded Mourinho to become the manager of Real Madrid on a three-year deal. A day later, he was introduced at his first press conference for Madrid where it was announced that both Zinedine Zidane and Paul Clement will be his assistants. On 1 September 2013, the long-awaited transfer from Tottenham of Gareth Bale was announced. The transfer of the Welshman was reportedly the new world record signing, with the transfer price approximated at €100 million. In Ancelotti's first season at the club, Real Madrid won the Copa del Rey, with Bale scoring the winner in the final against Barcelona. On 24 May, Real Madrid defeated city rivals Atlético Madrid in the 2014 Champions League Final, winning their first European title since 2002, and becoming the first team to win ten European Cups/Champions League titles, an achievement known as "La Décima".
					After winning the 2014 Champions League, Real Madrid signed goalkeeper Keylor Navas, midfielder Toni Kroos and attacking midfielder James Rodríguez. The club won the 2014 UEFA Super Cup against Sevilla, with two goals by Cristiano Ronaldo, the club's 79th official trophy. During the last week of the 2014 summer transfer window, Real Madrid sold two players key in the previous season's successes—Xabi Alonso to Bayern Munich and Ángel Di María to Manchester United, the latter for an English record fee of €75 million. This decision from the club was surrounded by controversy, with Cristiano Ronaldo stating, "If I was in charge, maybe I would have done things differently," while Carlo Ancelotti admitted, "We must start again from zero."
					After a slow start to the 2014–15 La Liga season, which included defeats to Atlético Madrid and Real Sociedad, Real Madrid went on a record-breaking winning streak, which included wins against Barcelona and Liverpool, surpassing the previous Spanish record of 18 successive wins set by Frank Rijkaard's Barça in the 2005–06 season. In December 2014, the club extended their winning streak to 22 games with a 2–0 win over San Lorenzo in the 2014 FIFA Club World Cup final, thus ending the calendar year with four trophies. Their 22-game winning streak ended in their opening game of 2015 with a loss to Valencia, leaving the club two short of equalling the world record of 24 consecutive wins.The club failed to retain the Champions League (losing 3–2 on aggregate against Juventus in the semi-finals), the Copa del Rey (4–2 aggregate loss to Atlético), and failed to land the league title (finishing two points and a place behind champions Barcelona), shortcomings that all preceded Ancelotti's sacking on 25 May 2015.
					On 3 June 2015, Rafael Benítez was confirmed as the new Real Madrid manager, signing a three-year contract. Real Madrid remained unbeaten in the league until a 3–2 loss at Sevilla in the 11th matchday. This was followed by a 0–4 home loss in the first Clásico of the season against Barcelona. Real played Cádiz in the Copa del Rey Round of 32, winning away 1–3 in the first leg. However, they fielded an ineligible player in Denis Cheryshev as he was suspended for that match, resulting in the second leg being cancelled and Real being disqualified. Meanwhile, Real topped their UEFA Champions League group with 16 points. He was sacked on 4 January 2016, following allegations of unpopularity with supporters, displeasure with players and a failure to get good results against top sides. At the time of sacking, Real were third in La Liga, four points behind leaders Atlético Madrid and two points behind arch-rivals Barcelona (with a game in hand).
					On 4 January 2016, Benítez's departure was announced along with the promotion of Zinedine Zidane to his first head coaching role. Zidane previously worked as assistant to Benítez's predecessor Carlo Ancelotti and, since 2014, had occupied the helm of reserve team Real Madrid Castilla. Zidane's coaching debut for Madrid was marked by a 5–0 home victory over Deportivo in La Liga on 9 January 2016, with Gareth Bale scoring a hat-trick. On 28 May, Real Madrid won their 11th Champions League title, extending their record for most successes in the competition, with Cristiano Ronaldo scoring the decisive penalty in a shootout win over Atlético Madrid in the final. On 10 December 2016, Madrid won 3–2 against Deportivo de La Coruña, which was their 35th straight match without a loss, which set a new record. On 18 December 2016, Madrid defeated Japanese club Kashima Antlers 4–2 in the final of the 2016 FIFA Club World Cup, with Cristiano Ronaldo scoring a hat-trick.
					</p>
					<div class="divdivdiv">
						<iframe width="854" height="480" src="https://www.youtube.com/embed/ihfuFl57Z6Y" frameborder="0" allowfullscreen id="ifr1"></iframe>
						<iframe width="854" height="480" src="https://www.youtube.com/embed/5mZ7fvc4rNA" frameborder="0" allowfullscreen></iframe>
					</div>
			</div>
			<?php  
				include("footer.php");
			?>

		</div>
	</body>
</html>